//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF272_ProjectAssignment3Del02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERDETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDERDETAIL()
        {
            this.ORDERITEMs = new HashSet<ORDERITEM>();
            this.ORDERPAYMENTs = new HashSet<ORDERPAYMENT>();
        }
    
        public int Order_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<int> Supplier_ID { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERITEM> ORDERITEMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERPAYMENT> ORDERPAYMENTs { get; set; }
    }
}
