//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF272_ProjectAssignment3Del02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERPAYMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDERPAYMENT()
        {
            this.COMPLETEDTRANSACTIONs = new HashSet<COMPLETEDTRANSACTION>();
        }
    
        public int OPayment_ID { get; set; }
        public Nullable<int> Order_ID { get; set; }
        public Nullable<int> Payment_Type_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<int> Supplier_ID { get; set; }
        public Nullable<decimal> Payment_Amount { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPLETEDTRANSACTION> COMPLETEDTRANSACTIONs { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual ORDERDETAIL ORDERDETAIL { get; set; }
        public virtual PAYMENTTYPE PAYMENTTYPE { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
