//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF272_ProjectAssignment3Del02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALELINE
    {
        public int SaleLine_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> Sale_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual SALE SALE { get; set; }
    }
}
