//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF272_ProjectAssignment3Del02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALEPAYMENT
    {
        public int SPayment_ID { get; set; }
        public Nullable<int> Sale_ID { get; set; }
        public Nullable<int> Payment_Type_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public Nullable<decimal> Payment_Amount { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual PAYMENTTYPE PAYMENTTYPE { get; set; }
        public virtual SALE SALE { get; set; }
    }
}
