//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF272_ProjectAssignment3Del02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEMUSER
    {
        public string UserName { get; set; }
        public string User_Password { get; set; }
        public string User_Password_Question { get; set; }
        public string User_Password_Answer { get; set; }
        public Nullable<int> Access_Level_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
    
        public virtual ACCESSLEVEL ACCESSLEVEL { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
